name: mikrotik_manager_flutter
description: Flutter app to manage MikroTik hotspot users via RouterOS binary API.
publish_to: "none"
version: 1.0.0+1

environment:
  # تم تعديل هذا السطر للسماح بـ Dart SDK 3.1.0
  sdk: ">=3.35.0 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  router_os_client: ^2.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # قد تحتاج إلى تقليل هذا الإصدار إذا كان يعتمد على Dart أحدث

flutter:
  uses-material-design: true
  assets:
    - assets/
